version: "3.3"
services:
  spark-master:
    image: kana1/spark-master:latest
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - spark-network
    environment:
      - "SPARK_LOCAL_IP=spark-master"
      - "SPARK_MASTER_PORT=7077"
      - "SPARK_MASTER_WEBUI_PORT=8080"
      - "SPARK_PUBLIC_DNS=localhost"
    command: "/start-master.sh"
  spark-worker:
    image: kana1/spark-worker:latest
    depends_on:
      - spark-master
    ports:
      - 8080
    networks:
      - spark-network
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_WEBUI_PORT=8080"
      - "SPARK_WORKER_CORES=2"
      - "SPARK_WORKER_MEMORY=1g"
    command: "/start-worker.sh"
  livy-spark:
    image: kana1/livy-spark:latest
    container_name: livy-spark
    hostname: livy-spark
    depends_on:
      - spark-master
    ports:
      - "8998:8998"
    networks:
      - spark-network
    environment:
      - "SPARK_MASTER_ENDPOINT=spark://spark-master:7077"
      - "DEPLOY_MODE=client"
    command: "/start-livy.sh"
networks:
  spark-network:
    driver: bridge
    ipam:
      driver: default
